init commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,6 +1,20 @@
 name: Django CI
 
-on: [push, pull_request]
+on:
+  push:
+    branches:
+      - main  # Deploy only to main branch
+  pull_request:
+    branches:
+      - main  # Run checks only on PRs to main
+
+env:
+  SECRET_KEY: ${{ secrets.SECRET_KEY }}
+  DB_NAME: ${{ secrets.DB_NAME }}
+  DB_USER: ${{ secrets.DB_USER }}
+  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+  DB_HOST: postgres
+  DB_PORT: 5432
 
 jobs:
   lint:
@@ -12,7 +26,7 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: "3.12"
+          python-version: "3.13"
 
       - name: Install flake8
         run: |
@@ -22,13 +36,24 @@ jobs:
       - name: Run flake8
         run: flake8 .
 
-
   test:
     needs: lint
     runs-on: ubuntu-latest
-    env:
-      SECRET_KEY: ${{ secrets.SECRET_KEY }}
 
+    services:
+      postgres:
+        image: postgres:latest
+        env:
+          POSTGRES_DB: ${{ secrets.DB_NAME }}
+          POSTGRES_USER: ${{ secrets.DB_USER }}
+          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
+        ports:
+          - 5432:5432
+        options: >-
+          --health-cmd "pg_isready -U $POSTGRES_USER"
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
 
     steps:
       - name: Check out code
@@ -37,66 +62,44 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: "3.12"
+          python-version: "3.13"
+
+      - name: Cache Poetry dependencies
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.cache/pypoetry/virtualenvs
+            ~/.cache/pypoetry/artifacts
+          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
+
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install -r requirements.txt
+          pip install poetry
+          poetry config virtualenvs.create false
+          poetry install --no-root
 
       - name: Run tests
         run: python manage.py test
 
-  build:
-    runs-on: ubuntu-latest
+  deploy:
     needs: test
+    runs-on: ubuntu-latest
+    environment:
+      name: Production
+      url: your-production-url.com
 
     steps:
       - name: Check out code
-        uses: actions/checkout@v3
-
-      - name: Log in to Docker Hub
-        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
-
-      - name: Build Docker image
-        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/atomichabits:${{ github.sha }} .
-
-      - name: Push Docker image to Docker Hub
-        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/atomichabits:${{ github.sha }}
-
-  deploy:
-    needs: build
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Set up SSH agent
-        uses: webfactory/ssh-agent@v0.9.0
+        uses: appleboy/ssh-action@v1.0.0
         with:
-          ssh-private-key: ${{ secrets.SSH_KEY }}
-
-#      - name: Deploy to server
-#        run: |
-#          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60" ./ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}
-#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
-#              cd /home/ekatesting/app
-#              docker-compose down
-#              docker rm -f $(docker ps -aq)
-#              docker stop atomichabits || true
-#              docker rm atomichabits || true
-#              docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/atomichabits:${{ github.sha }}
-#              docker run -d --name atomichabits -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/atomichabits:${{ github.sha }}
-#          EOF
-      - name: Deploy to server
-        run: |
-          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60" ./ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'               
-              docker stop atomichabits || true
-              docker rm atomichabits || true
-              cd /home/ekatesting/app
-              docker-compose down || true
-              docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/atomichabits:${{ github.sha }}
-              docker run -d --name atomichabits -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/atomichabits:${{ github.sha }}
-          EOF
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USER }}
+          key: ${{ secrets.SSH_KEY }}
+          script: |
+            set -e # Exit immediately if a command exits with a non-zero status.
+            cd dev/atomichabits_deploy
+            git pull
+            docker compose down
+            docker compose up -d --build
