init commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,13 +22,11 @@ jobs:
       - name: Run flake8
         run: flake8 .
 
-
   test:
     needs: lint
     runs-on: ubuntu-latest
     env:
       SECRET_KEY: ${{ secrets.SECRET_KEY }}
-
 
     steps:
       - name: Check out code
@@ -84,8 +82,8 @@ jobs:
               echo "Removing existing container..."
               sudo docker rm drf-proj-db-1 || true                            
               echo "Pulling new image..."
-              sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/drf-proj:${{ github.sha }}
+              sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/drf-proj:${{ github.sha }} || { echo "Failed to pull image"; exit 1; }
               echo "Running new container..."
-              sudo docker run -d --name drf-proj-db-1 -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/drf-proj:${{ github.sha }}
+              sudo docker run -d --name drf-proj-db-1 -p 80:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/drf-proj:${{ github.sha }} || { echo "Failed to run container"; exit 1; }
           EOF
           echo "Deployment completed successfully."
